version: '3.8'

services:
  # Django application
  web:
    build: .
    command: gunicorn src.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=src.settings
      - DATABASE_URL=postgres://user:password@db:5432/dbname
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  # PostgreSQL database
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  # Redis service
  redis:
    image: redis:latest

  # Celery worker
  celery:
    build: .
    command: celery -A src worker --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=src.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  # Celery beat for periodic tasks
  celery-beat:
    build: .
    command: celery -A src beat --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=src.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  postgres_data:
